__default__:
  time: "2:00:00"
  cpus: 1
  mem: "4000M"
  jobname: "s.{rule}.{wildcards}"
  output: "logs/slurm-%A_%a.{rule}.{wildcards}.out"
  error: "logs/slurm-%A_%a.{rule}.{wildcards}.err"

collapseIntersectResults:
  mem: "20G"
  
calculate_effective_annots:
  mem: "20G"

test_enrichment:
  mem: "20G"

conditional_analysis:
  mem: "20G"
